config/routes.rb
Rails.application.routes.draw do

  get 'admin' => 'admin#index'
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :users
  resources :orders
  resources :line_items
  resources :carts

  get 'store/index'
  root 'store#index', as: 'store'

  resources :products do
    get :who_bought, on: :member
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<title>Pragprog Books Online Store</title>
<%= stylesheet_link_tag "application", media: "all",
    "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>

  </head>
<body class="<%= controller.controller_name %>">
<div id="banner">
<%= image_tag("logo.png") %>
<%= @page_title || "Pragmatic Store" %>
</div>
<div id="columns">
  <div id="side">
    <% if @cart %>
      <!-- <div id='cart'> -->
      <%= hidden_div_if(@cart.line_items.empty?, id: 'cart') do %>
        <%= render @cart %>
      <% end %>
      <!-- </div> -->
    <% end %>
  <ul>
<li><%= link_to 'Home', store_path %></li>
<li><a href="http://www..../faq">Questions</a></li> <li><a href="http://www..../news">News</a></li> <li><a href="http://www..../contact">Contact</a></li>
</ul> 
<% if session[:user_id] %> <ul>
<li><%= link_to 'Orders', orders_path %></li> <li><%= link_to 'Products', products_path %></li> <li><%= link_to 'Users', users_path %></li>
</ul>
<%= button_to 'Logout', logout_path, method: :delete %> <% end %>
</div>
  <div id="main">
    <%= yield %>
  </div>
</div>
</body>
</html>